### ISSUE TITLE
Module '"otterhttp-cookie"' declares 'serialize' locally, but it is not exported. <ArkTSCheck>

### ISSUE THREAD

**Issue by ipad4** [OtterJS/otterhttp#16]
serialize未导出
`Module '"otterhttp-cookie"' declares 'serialize' locally, but it is not exported. <ArkTSCheck>`

**Comment by Lordfirespeed** [comment]
It is exported, though: [see here](https://github.com/OtterJS/otterhttp/blob/a649bf868dce056e536f054ca5a2f7721a1f4efe/packages/cookie/src/index.ts#L69)

Can you provide a minimal reproducible example?
